### ISSUE TITLE
website not working 

### ISSUE THREAD

**Issue by ayoubelmohamedi** [mistergoodson/memory-management-simulator#1]
Hi, I went to https://www.jamiegoodson.co.uk/ for the interactive simulation, but its not working ?

**Comment by JamieGoodson** [comment]
Hey, sorry I don't host this on my website anymore (I made this years ago when I was in college). You can just download this repo yourself and double-click on `index.html` - it should open in your browser with the site running 🙂

**Comment by ayoubelmohamedi** [comment]
that's exactly what I did, nice project
